apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server
    spec:
      initContainers:
      - name: init-server
        image: {{ .Values.server.init.image }}
        command: [
          {{- range $k,$v := .Values.server.init.cmd }}
            '{{ $v }}',
          {{- end }} 
        ]
        args: ["
          {{- range $k,$v := .Values.server.init.args }}
            {{ $v | trim }}
          {{- end }} 
        "]
        volumeMounts:
        - name: server-env
          mountPath: {{ .Values.server.mounts.env }}
        - name: server-pages
          mountPath: {{ .Values.server.mounts.html }}
      containers:
      - image: {{ .Values.server.image }}
        name: server
        stdin: true 
        tty: true 
        command: ["{{ .Values.server.cmd }}"]
        volumeMounts:
        - name: server-env
          mountPath: {{ .Values.server.mounts.env }}
        - name: server-pages
          mountPath: {{ .Values.server.mounts.html }}
      volumes:
      - name: server-env
        configMap: 
          name: server-env
          items:
            - key: {{ .Values.server.envKey }}
              path: {{ .Values.server.envKey }}
      - name: server-pages
        configMap: 
          name: server-pages
