apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: server-tcp
  name: server-tcp
  namespace: custom-dev
spec:
  selector:
    app: server
  ports:
  - name: main-tcp
    port: 31500
    targetPort: 31500
    protocol: TCP
  - name: failover-tcp
    port: 31501
    targetPort: 31501
    protocol: TCP
