apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: server
  name: server
  namespace: default
spec:
  selector:
    app: server
  ports:
  - name: main-tcp
    port: {{ .Values.server.ports.main }}
    targetPort: {{ .Values.server.ports.main }}
    protocol: TCP
  - name: failover-tcp
    port: {{ .Values.server.ports.failover }}
    targetPort: {{ .Values.server.ports.failover }}
    protocol: TCP
