apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
      app: client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - image: {{ .Values.client.image }}
        name: client
        stdin: true 
        tty: true 
        command: ["{{ .Values.client.cmd }}"]
        args: ["$(SERVER_TCP_SERVICE_HOST)", $(SERVER_TCP_SERVICE_PORT)]
        volumeMounts:
        - mountPath: {{ .Values.client.mounts.env }}
          name: client-env
      volumes:
      - name: client-env
        configMap: 
          name: client-env
          items:
            - key: {{ .Values.client.envKey }}
              path: {{ .Values.client.envKey }}
