apiVersion: v1
kind: Service
metadata:
  name: server-tcp
spec:
  selector:
    app.kubernetes.io/name: server
  ports:
    - protocol: TCP
      port: 44555
      targetPort: 44555
    - protocol: TCP
      port: 44666
      targetPort: 44666