server:
  init:
    cmd: ['sh', '-c']
    image: busybox:1.28
    args:
      - set -x;
      - cp /tmp/envvars/.env /tmp/envfile/.env;
      - chown -R 10001:10001 /tmp/envfile/.env;
      - chmod 644 /tmp/envfile/.env;
      - echo 'Setting up DATABASE.HOST in /tmp/envfile/.env..';
      - sed -i -e \"s/DATABASE.HOST=127.0.0.1/DATABASE.HOST=$MYSQL_SERVICE_HOST/g\" /tmp/envfile/.env;
      - sed -i -e \"s/DATABASE.HOST=3306/DATABASE.PORT=$MYSQL_SERVICE_PORT/g\" /tmp/envfile/.env;
      - ls -ltr /tmp/envfile/.env && cat /tmp/envfile/.env;
      - chown -R 10001:10001 /tmp/html;
      - chmod 664 /tmp/html/*.html;
      - ls -ltr /tmp/html;
  cmd: /bin/server
  image: 127.0.0.1:5000/v2/rust-server:1.0
  ports:
    main: 31500
    failover: 31501
  mounts:
    env: /tmp/envvars
    envWriteable: /tmp/envfile
    html: /tmp/html
  envKey: .env