apiVersion: v1
kind: ConfigMap
metadata:
  namespace: custom-dev
  name: mysql-config
  labels:
    app: mysql-config
data:
  my.cnf: |
    [client]
    port                          = 3306
    socket                        = /var/run/mysqld/mysqld.sock
    default-character-set         = UTF8MB4
    user=root
    password=password

    [mysql]
    default-character-set         = UTF8MB4

    [mysqld]
    default-authentication-plugin = caching_sha2_password
    server-id                     = 1
    user                          = mysql
    basedir                       = /bin/mysql-8.0/
    datadir                       = /var/lib/mysql
    socket                        = /var/lib/mysql/mysql.sock
    secure-file-priv              = /var/lib/mysql-files
    tmpdir                        = /tmp
    character-set-server          = UTF8MB4
    pid-file                      = /var/run/mysqld/mysqld.pid
    lc-messages-dir               = /usr/share/mysql-8.0/english
    lc-messages                   = en_US
    log-bin                       = mysql-0-bin
    bind-address                  = mysql-0.mysql.custom-dev.svc.cluster.local


    skip-host-cache
    skip-name-resolve

    #!includedir /etc/mysql/conf.d/
immutable: true