apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: custom-dev
  name: mysql-pvc
  labels:
    app: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi