apiVersion: v1
kind: Service
metadata:
  namespace: custom-dev
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql